//CUSTOMER API
const ERROR_API_CUSTOMER_NEED_ID_CUSTOMER = 'ERROR_API_CUSTOMER_NEED_ID_CUSTOMER'
const ERROR_API_CUSTOMER_NEED_BODY_DATA = 'ERROR_API_CUSTOMER_NEED_BODY_DATA'
const ERROR_API_CUSTOMER_NEED_PAGE_QUERY = 'ERROR_API_CUSTOMER_NEED_PAGE_QUERY'

//SERVER
const SERVER_SUCCESS_RUNNING = 'SERVER_SUCCESS_RUNNING'
const SERVER_ERROR_RUNNING = 'SERVER_ERROR_RUNNING'

//DB
const DB_SUCCESFULLY_CONNECTED = 'DB_SUCCESFULLY_CONNECTED'

module.exports = {
    //customer
    ERROR_API_CUSTOMER_NEED_ID_CUSTOMER,
    ERROR_API_CUSTOMER_NEED_BODY_DATA,
    ERROR_API_CUSTOMER_NEED_PAGE_QUERY,
    //db
    SERVER_SUCCESS_RUNNING,
    //server
    DB_SUCCESFULLY_CONNECTED,
    SERVER_ERROR_RUNNING,
}