export const CUSTOMERS_GET_BY_PAGE_REQUEST = 'CUSTOMERS_GET_BY_PAGE_REQUEST'
export const CUSTOMERS_GET_BY_PAGE_SUCCESS = 'CUSTOMERS_GET_BY_PAGE_SUCCESS'
export const CUSTOMERS_GET_BY_PAGE_FAIL = 'CUSTOMERS_GET_BY_PAGE_FAIL'

export const CUSTOMERS_UPDATE_REQUEST = 'CUSTOMERS_UPDATE_REQUEST'
export const CUSTOMERS_UPDATE_SUCCESS = 'CUSTOMERS_UPDATE_SUCCESS'
export const CUSTOMERS_UPDATE_FAIL = 'CUSTOMERS_UPDATE_FAIL'

export const CUSTOMER_DELETE_REQUEST = 'CUSTOMER_DELETE_REQUEST'
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS'
export const CUSTOMER_DELETE_FAIL = 'CUSTOMER_DELETE_FAIL'

export const CUSTOMER_CREATE_REQUEST = 'CUSTOMER_CREATE_REQUEST'
export const CUSTOMER_CREATE_SUCCESS = 'CUSTOMER_CREATE_SUCCESS'
export const CUTSOMER_CREATE_FAIL = 'CUTSOMER_CREATE_FAIL'

export const CUSTOMER_GET_REQUEST = 'CUSTOMER_GET_REQUEST'
export const CUSTOMER_GET_SUCCESS = 'CUSTOMER_GET_SUCCESS'
export const CUSTOMER_GET_ERROR = 'CUSTOMER_GET_ERROR'